version: '3'

services: 
    kafka-1:
      build: kafka_node
      ports:
        - 9095:9092
      environment:
        KAFKA_ADVERTISED_HOST_NAME: kafka.test.local
        KAFKA_ADVERTISED_PORT: 9095
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LOG_DIRS: /kafka/logs
        KAFKA_BROKER_ID: 500
        KAFKA_offsets_topic_replication_factor: 2
      volumes: 
        - /var/run/docker.sock:/var/run/docker.sock
        - ./vol/501:/kafka

    kafka-2:
      build: kafka_node
      ports:
        - 9096:9092
      environment:
        KAFKA_ADVERTISED_HOST_NAME: kafka2.test.local
        KAFKA_ADVERTISED_PORT: 9096
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LOG_DIRS: /kafka/logs
        KAFKA_BROKER_ID: 501
        KAFKA_offsets_topic_replication_factor: 2
      volumes: 
        - /var/run/docker.sock:/var/run/docker.sock
        - ./vol/501:/kafka

    zookeeper:
      #build: zookeeper_node
      image: wurstmeister/zookeeper
      ports:
        - 2181:2181
